### NUMPY 01

Numpy is the most basic and a powerful package for working with data in python.Pandas and Scikit Learn both are built on Numpy. At the core numpy provides the excellent ndarray objects, short for n-dimensional array. 

In [3]:
## Creatin a 1D array from a python list
import numpy as np
list1 = [0,1,2,3,4]
array1d = np.array(list1)

In [4]:
array1d

array([0, 1, 2, 3, 4])

In [5]:
type(array1d)

numpy.ndarray

The difference between an array and a list is - arrays are designed to handle vectorized operations while a python list is not, which means if you apply a function it is performed on every item in the array rather on the whole array object.

In [7]:
## Example -
## list1 + 2 - will give an error whereas -
array1d + 2 # will perform the array operation

array([2, 3, 4, 5, 6])

-- Numpy array size cannot be increased once created, we have to create a new arrya for that but in list it can be done.

Creating a 2d Array Matrix - list of list 

In [9]:
list2d = [[0,1,2], [3,4,5],[6,7,8]]

In [10]:
list2d

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [11]:
type(list2d)

list

We can set a specific datatype by setting the dtype argument, example - float, int, bool, str, object

In [13]:
# Creating a float 2d Array -
arr2d_f = np.array(list2d, dtype = 'float')
arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [14]:
arr2d_o = np.array(list2d, dtype ='object')

In [16]:
arr2d_o

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=object)

To control the memory allocations you may choose to use one of flaot32, float64, int8, int16, int32

Creating a Boolean array -

In [18]:
arr_boo = np.array([1,0,10], dtype = 'bool')
arr_boo

array([ True, False,  True])

Converting an array back to a list - 

In [33]:
arr = np.array([1,2,3])
listt = arr.tolist()
listt
type(listt)

list

In [39]:
arr2d = np.array(list2d) ## multidimensional array to list
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
list22 = arr2d.tolist()

In [41]:
list22

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

To summarise the main differences with python list and numpy array are -

+ Array support vectorised operations while lists don't
+ Once an array is created you cannot change it's size, will have to create or overwrite the existing one
+ Every array has one and only one dtype and all items in ti should be of that dtype
+ An equivalent numpy array occupied much less space than a python list of lists

Exploring a numpy array -
+ Dimension of an array = ndim
+ How many items present in the each dimension = shape
+ What is the datatype of a numpy array = dtype
+ What is the total number of items in it = size
+ Samples of first few items in the array is through indexing

In [43]:
# Creating a 2D array with 3 rows and 4 columns
list2 = [[1,2,3,4], [2,3,4,5], [2,3,4,5]]
arrr2 = np.array(list2, dtype = 'float')
arrr2

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [48]:
# Shape 
print('Shape of the array : ', arrr2.shape)

# dtype 
print('Data Type of the array : ', arrr2.dtype)

# size
print("Size of the array : ", arrr2.size)

# ndim
print('Num dimensions :', arrr2.ndim)

Shape of the array :  (3, 4)
Data Type of the array :  float64
Size of the array :  12
Num dimensions : 2


In [49]:
#### How to extract specific items from an array / Indexing - 
arrr2

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [2., 3., 4., 5.]])

In [57]:
arrr2[:1]

array([[1., 2., 3., 4.]])

In [63]:
#### How to represent missing values and infinite
# insert a nan and an inf
arrr2[1,1] = np.nan # not a number
arrr2[1,2] = np.inf # infinite 
arrr2

array([[ 1.,  2.,  3.,  4.],
       [ 2., nan, inf,  5.],
       [ 2.,  3.,  4.,  5.]])

In [66]:
arrrr2 = np.array([[1,2,3,4],[2,3,4,5]])

In [67]:
# How to compute mean, min, max on the ndarray
print("Mean value is: ", arrrr2.mean())
print("Max value is: ", arrrr2.max())
print("Min value is: ", arrrr2.min())

Mean value is:  3.0
Max value is:  5
Min value is:  1


In [68]:
## Row wise and column wise min - amin
print("Column wise minimum: " , np.amin(arrrr2, axis = 0))
print("Row wise minimum: " , np.amin(arrrr2, axis = 1))

Column wise minimum:  [1 2 3 4]
Row wise minimum:  [1 2]


Computing the minimum row wise is fine, but if you want to do some other computation/ function row-wise. It can be done using np.apply_over_axis discussed later


In [69]:
## Cumulative sum
np.cumsum(arrrr2)

array([ 1,  3,  6, 10, 12, 15, 19, 24])

Creating new array from existing array- 

If you just assign a portion of an array to another arry the new array you just created actually refes to the parent array in the memory and alteration in the new array will cause changes in the parent array, so to avoid this using copy() function will help

In [73]:
arr2a = arrrr2[:2,:2].copy()

In [75]:
arr2a

array([[1, 2],
       [2, 3]])

reshaping and flattening multidimensional arrays- 
Reshaping is changing the arrangment of items so that the shape of the array changes while maintaining the same number of dimensions. Flattening howere will convert a multidimensional array to a flat 1D array and not any other shape

In [78]:
## Reshaping a 3x4 aaray to 4x3 array
arrr2.reshape(4,3)

array([[ 1.,  2.,  3.],
       [ 4.,  2., nan],
       [inf,  5.,  2.],
       [ 3.,  4.,  5.]])

Difference between flatten() and ravel() for flattening the multidimensional arrays
- The difference between ravel and flatten is the new array created using ravel is actually a reference to the parent

In [79]:
## Flatten 
arr2a.flatten()

array([1, 2, 2, 3])

In [82]:
arr2a.ravel() ## points to the original array

array([1, 2, 2, 3])

How to create sequences, repetitions and random numbers using numpy - The np.arange function comes in handy to create customised number sequences as ndarray

In [83]:
#Lower limit is 0 to be default
print(np.arange(5))

[0 1 2 3 4]


In [84]:
# 0 to 9 
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [85]:
# 0 to 9 with step of 2
print(np.arange(0,10,2))

[0 2 4 6 8]


In [86]:
# 10 to 1 decreasing order
print(np.arange(10,0,-1))

[10  9  8  7  6  5  4  3  2  1]


Note - You can set the starting and end positions using np.arange. But if you are focussed on the number of items in the array you will have to manually calcualte the appropriate step value.
Say you want to create an array of exactly 10 numbers between 1 and 50.

In [87]:
#using np.linspace
#start at 1 and end at 50 
np.linspace(start = 1, stop = 50, num = 10, dtype = int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

the numbers are not equally spaced because of the rounding 

 Similar to np.linspace, there is also np.logspace which rises in a logarithmic scale.In no.logspace the given start valye is actually base start and ends with base stop with a default based of 10

In [92]:
# limit the number of digits after the decimal to 2
np.set_printoptions(precision = 2)

In [93]:
# start at 10^1 and end at 10^50
np.logspace(start = 1, stop = 50, num = 10, base = 10)

array([1.00e+01, 2.78e+06, 7.74e+11, 2.15e+17, 5.99e+22, 1.67e+28,
       4.64e+33, 1.29e+39, 3.59e+44, 1.00e+50])

How to create repeating sequence - np.tile will repeat a whole list or array n times. Whereas np.repeat repeats each item n times



In [96]:
a = [1,2,3]

#Repeat whole of 'a' two times
print('Tile :' , np.tile(a,2))

Tile : [1 2 3 1 2 3]


In [97]:
# Repeat each element of 'a' two times
print('Repeat : ', np.repeat(a,2))

Repeat :  [1 1 2 2 3 3]


How to generate random numbers - The random module provides nice functions to generate random numbers (and also statistical distributions) of any given shape

In [98]:
# Random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[0.08 0.66]
 [0.52 0.57]]


In [99]:
# Normal distribution with mean = 0 and variance = 1 of shape 2,2
print(np.random.randn(2,2))

[[-0.22 -0.7 ]
 [ 1.84 -0.44]]


In [100]:
#Random integers between [0,10) of shape 2,2
print(np.random.randint(0, 10, size = [2,2]))

[[8 5]
 [2 8]]


In [101]:
# One random number [0,1)
print(np.random.random())

0.19140499467196137


In [102]:
# Random number between [0,1) of shape 2,2
print(np.random.random(size = [2,2]))

[[0.85 0.55]
 [0.37 0.13]]


In [104]:
# Pick 10 items from a given list with equal probability 
print(np.random.choice(['a', 'e','i','o','u'], size = 10))

['i' 'a' 'a' 'e' 'u' 'o' 'u' 'e' 'a' 'i']


In [105]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a','e','i','o','u'], size = 10, p = [0.3, .1, 0.1, 0.4, 0.1])) # pick more o's

['a' 'o' 'u' 'e' 'a' 'i' 'o' 'a' 'o' 'o']


Now everytime you run any of the above functions, you get a different set of random numbers 
If you want to repeat the same set of random numbers every time, you need to set the seed or the random state. The seed can be any value. The only requirement is you must set the seed to the same value every time you want to generate the same set of random numbers

Once np.random.RandomState is created all the functions of the np.random module becomes available to the created randomstate object

In [106]:
# Created the random state
rn = np.random.RandomState(100)

In [107]:
# Create random numbers between [0,1) of shape 2,2
print(rn.rand(2,2))

[[0.54 0.28]
 [0.42 0.84]]


In [108]:
# Set the random seed
np.random.seed(100)

In [109]:
# Create random numbers between [0,1) of shape 2,2
print(np.random.rand(2,2))

[[0.54 0.28]
 [0.42 0.84]]


How to get the unique items and the counts - The np.unique method can be used to get the unique items. If you want the repetition coutns of each item, set the return_coutns parameter to True.


In [110]:
# Create random integers of size 10 between [0,10)
np.random.seed(100)
arr_rand = np.random.randint(0,10, size = 10)
print(arr_rand)

[8 8 3 7 7 0 4 2 5 2]


In [111]:
# Get the unique items and their counts
uniqs, counts = np.unique ( arr_rand, return_counts = True)
print("Unique items: ", uniqs)
print("Counts : ", counts)

Unique items:  [0 2 3 4 5 7 8]
Counts :  [1 2 1 1 1 2 2]


Continued in Numpy 02 .. 